# Generated by Django 3.2 on 2021-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_moderatorA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_moderatorB',
            field=models.BooleanField(default=False),
        ),
    ]
