# Generated by Django 3.2 on 2021-05-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_historicalreproduccionesmodel_reproduccionesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreproduccionesmodel',
            name='id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reproduccionesmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
