# Generated by Django 3.2 on 2021-05-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210503_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
