# Generated by Django 3.2 on 2021-05-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_suscribed',
            field=models.BooleanField(),
        ),
    ]
