# Generated by Django 3.2 on 2021-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210512_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreproduccionesmodel',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reproduccionesmodel',
            name='fecha',
            field=models.DateField(),
        ),
    ]
