# Generated by Django 3.2 on 2021-05-12 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210512_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduccionesmodel',
            name='genero',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalReproduccionesModel',
        ),
    ]
