# Generated by Django 3.2 on 2021-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210512_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
    ]
