# Generated by Django 3.2 on 2021-05-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_customuserevent_musicevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='musicevent',
            name='pgh_obj',
        ),
        migrations.DeleteModel(
            name='CustomUserEvent',
        ),
        migrations.DeleteModel(
            name='MusicEvent',
        ),
    ]
