# Generated by Django 3.2 on 2021-05-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210527_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
